/* Practice: l3p5.sas step 1 */

%let ex_reduced=
LIFETIME_GIFT_COUNT LAST_GIFT_AMT MEDIAN_HOME_VALUE 
FREQUENCY_STATUS_97NK MONTHS_SINCE_LAST_GIFT  nses_ 
mi_DONOR_AGE PCT_MALE_VETERANS PCT_MALE_MILITARY
PCT_WWII_VETERANS LIFETIME_AVG_GIFT_AMT cluster_swoe 
PEP_STAR nurbu nurbt home01 nurbr DONOR_AGE STATUS_FL 
MOR_HIT_RATE nses4 INCOME_GROUP RECENT_STAR_STATUS IN_HOUSE 
WEALTH_RATING PUBLISHED_PHONE PCT_OWNER_OCCUPIED nurbs;
